### ISSUE TITLE
Publish a new release with latest dependency

### ISSUE THREAD

**Issue by bitinn** [PhilWaldmann/openrecord#101]
This commit to update `knex` addresses a vulnerability (even though the vulnerability only affects MSSQL), I would love to see a new release so that my code isn't stuck at vulnerable due to `openrecord` 2.10.2 still depends on older vulnerable version of `knex`.

**Comment by bitinn** [comment]
Missed the commit link:

https://github.com/PhilWaldmann/openrecord/commit/5022e06c1469407bd0ff828cad5b0cdd3e5c4736

**Comment by PhilWaldmann** [comment]
I've just published `openrecord@2.10.4` with `knex` version 0.20.2

Thanks,
Philipp
