### ISSUE TITLE
How can i make raw sql query?

### ISSUE THREAD

**Issue by Feelthewind** [PhilWaldmann/openrecord#102]
Hi, author.

I wonder how i can make raw sql query.

Is there any example or something else to solve this?

Plus, I also wonder how i can define models when primary key is more than one.

**Comment by PhilWaldmann** [comment]
Hi @Feelthewind 

use `Model.raw("SQL QUERY", arguments)` or `store.connection.raw("SQL QUERY")` (see [knex](https://knexjs.org/#Schema-raw))
