### ISSUE TITLE
Please update CONTRIBUTING.md

### ISSUE THREAD

**Issue by Romaboy** [PhilWaldmann/openrecord#107]
Currently it is almost blank.
It's not clear how to run specific test, how to setup databases, etc.

I replaced all `user: 'postgres'` to my user because I don't have user postgres, then I tried to run specific test and got `beforePG`, then I added `require('./__helper')` to the test and currently stuck at:

` TypeError: Cannot read property 'be' of undefined`

For the test codes like 
```js
ArrayTest.definition.attributes[attr].type.name.should.be.equal(...)
```

FIxed this by adding `chai` dependency and
```js
require('chai').should();
```
To the top of the test

P.S I think this library it great, it must live on, must be friendly to contributors

**Comment by PhilWaldmann** [comment]
Thanks for the feedback.
I'll try to update the readme and make it easier to get started in the upcoming days 

The test setup is defined in the [travis.yml](https://github.com/PhilWaldmann/openrecord/blob/master/.travis.yml) file. But it's not designed for humans ;)
