### ISSUE TITLE
Help Wanted. Database query builder

### ISSUE THREAD

**Issue by samuelthompson189** [PhilWaldmann/openrecord#110]
Heya, Is there the ability to use both models and a query builder? I cannot find anything in the docs

i.e. something like this would be perfect
```
const store = new Store({
  file: 'path/to/db.sqlite'
})

store.ready(async () => {
   const user = await store.table('users').where('id', 1).get()
})
```

Cheers

**Comment by PhilWaldmann** [comment]
openrecord uses [knex](https://knexjs.org/) for all SQL stores. To get your example working, you'll need to access the `store.connection`.
```js
const store = new Store({
  file: 'path/to/db.sqlite'
})

store.ready(async () => {
   const user = await store.connection.table('users').where('id', 1).get()
})
```

**Comment by samuelthompson189** [comment]
Awesome, thanks for the help!
