### ISSUE TITLE
Custom table name?

### ISSUE THREAD

**Issue by bs1180** [PhilWaldmann/openrecord#25]
Thanks for a great library. Is there a way to specify the table name? From the [relevant code](https://github.com/PhilWaldmann/openrecord/blob/39d9f28188bb0b300f18e19fd0304111e20c2cce/lib/stores/sql/table_name.js) it looks like the inflection can be overridden in the config - but not in the model definition?

**Comment by arxony** [comment]
Yes, you can specify the table name in the global config, but not in the model definition:
{
  type      : 'postgres',
  host      : '127.0.0.1',
  user      : 'user',
  password  : 'password',
  database  : 'databasename',
  charset   : 'utf8',
  models    : __dirname + '/../models/**/*.js',
  migrations: __dirname + '/../migrations/*',
  plugins   : [],
  global    : true,
  inflection: { backgroundjob_summaries: 'backgroundjob_summary' }
}
The sql table name is 'backgroundjob_summary'.

**Comment by PhilWaldmann** [comment]
Hi,

at the current state it's not possible to overwrite the table name inside the model (for `sql` types). OpenRecord will read all table columns before it will invoke your model definition method.

The table name is a pluralized version of your model name (with underscores). It takes your model name either from your definition `store.Model('Foo', function(){...})`, or if you have one file per model it will take your file name.

What @arxony  pointed out is a way to overwrite the inflection behavior. For example: you have a model `Foo` and your table name is also called `foo`. OpenRecord will search for a table called `foos`. With the inflection config mentioned above you change that behavior and use table `foo` instead.

**Comment by bs1180** [comment]
Thanks for quick response. I can achieve what I'm looking for using the inflection method that @arxony explained, and although a method on the definition itself would be handy, it's not essential. I'll mark this as closed. 

Thanks again.

**Comment by incompletude** [comment]
It would be nice to have a property on the model to set the table name.
