### ISSUE TITLE
Test Failures

### ISSUE THREAD

**Issue by davesag** [PhilWaldmann/openrecord#26]
Hi @PhilWaldmann 

I am evaluating Node based ORM systems for use with a multi-database system that includes both traditional SQL (PG to be specific) and Redis (for caching) and OpenRecord looks great.

The only concern I have is the fact that your test suite is currently flagged as failing.  A quick look at [the Travis report](https://travis-ci.org/PhilWaldmann/openrecord) shows test fails for assigning of `primary_keys` which is a bit of a concern.
1. Do you expect these test failures to be resolved soon?
2. Is there a stable version I ought to be looking at?
3. Can you let me know of other users of OpenRecord I could speak to about their experiences?

Thanks

Dave

**Comment by PhilWaldmann** [comment]
Hi Dave,

jeah, the test suite currently fails on travis-ci. But it's not a big deal!
The failing tests are supposed to fail - but should be handled gracefully.

I'll fix it as soon as I've time to compare my local environment to travis.

Thanks,
Philipp

**Comment by davesag** [comment]
Good to hear. I'll keep an eye out.

**Comment by PhilWaldmann** [comment]
tests are running fine for node v0.10, v4 and v6
