### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by nareboy** [PhilWaldmann/openrecord#27]
Hi.
When i try to install, these error messages are presented:
npm WARN `git config --get remote.origin.url` returned wrong result (https://git
hub.com/tgriesser/knex.git) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (https://git
hub.com/tgriesser/knex.git) undefined
npm ERR! git clone https://github.com/tgriesser/knex.git undefined
npm ERR! git clone https://github.com/tgriesser/knex.git undefined
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

Something wrong with git url of knex.
I'm very sad, I really liked what I saw, =\

**Comment by arxony** [comment]
> npm ERR! not found: git
Seems like you need to install git or adapt your environment PATH variable.

**Comment by nareboy** [comment]
My Bad. 
I don't know how my os can lost git path environment. Simple suddenly happened!
Thank you very much for your attention.

Cheers.
