### ISSUE TITLE
WebSQL Support

### ISSUE THREAD

**Issue by putraxor** [PhilWaldmann/openrecord#28]
will it support WebSQL adapter?

**Comment by PhilWaldmann** [comment]
There is currently no WebSQL adapter, but implementing it shouldn't a big deal.
PRs welcome

**Comment by 7dir** [comment]
browser support?

**Comment by PhilWaldmann** [comment]
no yet. But I saw that [knex](http://knexjs.org/) (the underling module for all SQL things) has WebSQL support. If I have time I'll compile OpenRecord for the browser with REST and WebSQL support.

But as always: PRs are welcome!

**Comment by 7dir** [comment]
@PhilWaldmann thx

**Comment by ksouthworth** [comment]
What about support for Cordova, or more specifically, Ionic Framework, and their Ionic Native SQLite storage?  https://ionicframework.com/docs/native/sqlite/

That would be rad!

**Comment by PhilWaldmann** [comment]
I don't have any experience with cordova.
Currently knexjs handles all the sql stuff. As far as i can see we only need to redirect the final sql queries to the `executeSql()` method of `ionic-native/sqlite`.
Do you have any experience with ionic-native testing?

**Comment by PhilWaldmann** [comment]
Knexjs has dropped support for WebSQL and W3C has stopped working on the [sepcs](https://dev.w3.org/html5/webdatabase/)
