### ISSUE TITLE
Unable to install this very package

### ISSUE THREAD

**Issue by jekku** [PhilWaldmann/openrecord#30]
Hello.

I'm from South East Asia and I have tried installing this over

```
npm install --save openrecord pg
```

It hangs and npm won't continue

As a work around, I tried:

```
cd node_modules
git clone git@github.com:PhilWaldmann/openrecord.git
cd openrecord
npm install
```

I think one of the packages within your package.json is causing the install to hang. Can I get some help identifying which, and what to do? I'd also like if installing it in your region works, after you have cleaned your npm cache.

**Comment by PhilWaldmann** [comment]
Hi Jekku,

I know, some dependencies are outdated (something I want to fix in the coming weeks), but I can't find any problem installing the package. Unfortunately I don't have any influence on the regional distribution of npm. It's working fine in Europe.
do you have any logs (`npm-debug.log`)? Maybe you experiences a short network timeout.

**Comment by jekku** [comment]
It doesn't spew out pieces of STDERR, it hangs. Thus, no npm-debug.log. I'll try to wait it out for 30mins to an hour. God, third world internet is really horrible.

**Comment by jekku** [comment]
It installed JUST NOW O.o Closing this up. thanks anyway!

**Comment by PhilWaldmann** [comment]
Glad to hear that it's working now for you!
