### ISSUE TITLE
Postgresql's JsonB data type support request

### ISSUE THREAD

**Issue by arthurfranca** [PhilWaldmann/openrecord#39]
I see there is already hstore support.
But jsonb is better than json and hstore.

Any chance of [supporting it](https://www.postgresql.org/docs/9.6/static/functions-json.html)?

**Comment by PhilWaldmann** [comment]
yep. Implementation is was easy: cb4990e3836609781079db6dcfa8e76148c684a1 ;)
available in version `1.11.0`
