### ISSUE TITLE
how to use alias in requests

### ISSUE THREAD

**Issue by stts-x** [PhilWaldmann/openrecord#40]
if i write  myBase.Model('good').select("goods.id AS 'sku'").exec()
 i receive result with out field 'sku', and field goods.id = null

**Comment by PhilWaldmann** [comment]
add `.asRaw()` after the `select(...)` to get the raw output.
OpenRecord only processes the known fields in normal mode. With `.asRaw()` you could force it to output everything your db returns.

As an alternative you could add an offline attribute to your model definition:
```js
this.attribute('sku', Number)
```

**Comment by PhilWaldmann** [comment]
btw: I don't think it's necessary to use quotes around `sku`.
