### ISSUE TITLE
.toSql() return query string  with double quotes

### ISSUE THREAD

**Issue by stts-x** [PhilWaldmann/openrecord#42]
Calling `.toSql()` method I'm getting the string with double quotes instead of backquotes, which cause a syntax error. In lib/stores/sql/exec.js in 42 line I found a function, replacing backquotes with double quotes. What's the reason of this replacement? Basically, It turns initially correct SQL string to an incorrect one.

**Comment by PhilWaldmann** [comment]
you are right. I've used `toSql()` only for the tests.
I've just released a fix (version 1.11.1).

Thanks,
Philipp
