### ISSUE TITLE
Oracle support

### ISSUE THREAD

**Issue by westlakem** [PhilWaldmann/openrecord#53]
Oracle support would allow me to use this

**Comment by SampsonCrowley** [comment]
@westlakem Isn't Oracle Java? this a JavaScript library not a Java library

**Comment by SampsonCrowley** [comment]
after more research I'm guessing you mean OracleDB?

**Comment by PhilWaldmann** [comment]
The underlying module for all sql related stuff ([knex](http://knexjs.org/)) support oracle - so it should be easy to implement.
The only thing that's a little bit tricky is testing on travis-ci.
I've put it on the feature list for v2

**Comment by PhilWaldmann** [comment]
Hi @westlakem 
I've implemented basic [Oracle support](https://github.com/PhilWaldmann/openrecord/blob/v2/test/sql/oracle/attributes-test.js).
I don't have any in-depth experiences with Oracle, so it would be awesome if you could help me out and take a look at it.
