### ISSUE TITLE
Rolling back a migration

### ISSUE THREAD

**Issue by joeyparis** [PhilWaldmann/openrecord#56]
Is there any way to easily rollback a migration from outside of the internal source code?

**Comment by PhilWaldmann** [comment]
Hi,

nope, sorry. There is currently no cli or similar to do this.

**Comment by arthurfranca** [comment]
Maybe it would be a good idea to tell on docs that using Openrecord's migration feature is optional.
Found out that there's no need to set `migrations: 'path/to/my/migrations/*'` as one can use any migration tool it likes.

I myself used [pg-migrate](https://github.com/salsita/node-pg-migrate)

ORM-wise, openrecord is the best one out there after testing many other node orm contenders.

**Comment by PhilWaldmann** [comment]
The new docs will cover that. thanks
