### ISSUE TITLE
Can't get relations to work

### ISSUE THREAD

**Issue by matheusgrieger** [PhilWaldmann/openrecord#57]
Hi! I'm just starting to use this package, but I need some help since the docs are not complete as stated in other issues. I'm getting a "Can't find relation" error. Here is my setup:

```js
// ClutchUsers.model.js
module.exports = function ClutchUsers() {
  this.hasMany('clutch_user_permission')
      .hasMany('clutch_module', {through: 'clutch_user_permissions', primary_key: 'id', foreign_key: 'user'})

      .scope('active', function () {
        this.where({status: 1})
      })
}

// ClutchUserPermissions.model.js
module.exports = function ClutchUserPermissions () {
  this.belongsToMany('clutch_user')
      .belongsToMany('clutch_module')
}

// ClutchModules.model.js
module.export = function ClutchModules () {
  this.hasMany('clutch_user_permission')
      .hasMany('clutch_user', {through: 'clutch_user_permissions', primary_key: 'id', foreign_key: 'module'})
}
```

I tried following the examples but it is not working when I run something like this:

```js
store.ready(() => {
  const ClutchUsers = store.Model('ClutchUsers')
  ClutchUsers.active().include('clutch_modules').exec((records) => {
    console.log(records)
  })
})
```

For reference: table names are `clutch_users`, `clutch_user_permissions`, `clutch_modules`. Both users and modules have an `id` pk column, and the permissions table has `user` and `module` columns for each of them as fk.

Without `include` it works, but I also want the modules that each user has. What am I doing wrong?

Thank you and congratulations on this awesome package!

**Comment by PhilWaldmann** [comment]
Hi Matheus,

yep, I've found the problems:

- The `hasMany through` relation need the name of the target relation `clutch_module` - something that could be done better by OpenRecord (try the singular version of the relation name)
- The `hasMany through` relation does not need to know the primary or foreign key - it uses it from it's target relation.
- The relations of the `ClutchUserPermission` module needed extra info regarding it's relation keys (`module` and `user`). OpenRecord was searching for a `user_id` and `module_id` field.


here is a working example (with an sqlite3 store)
```js
var OpenRecord = require('./store')

var store = new OpenRecord({
  type: 'sqlite3',
  file: 'db-test.sqlite3'
})

/*
CREATE TABLE clutch_users(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, status integer);
CREATE TABLE clutch_user_permissions(id INTEGER PRIMARY KEY AUTOINCREMENT, user INTEGER, module INTEGER);
CREATE TABLE clutch_modules(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);
INSERT INTO clutch_users(name, status) VALUES ('A', 1);
INSERT INTO clutch_users(name, status) VALUES ('B', 0);
INSERT INTO clutch_modules(name) VALUES ('M1');
INSERT INTO clutch_modules(name) VALUES ('M2');
INSERT INTO clutch_user_permissions(user, module) VALUES (1, 1);
INSERT INTO clutch_user_permissions(user, module) VALUES (1, 2);
INSERT INTO clutch_user_permissions(user, module) VALUES (2, 2);
*/

store.Model('ClutchUser', function ClutchUsers() {
  this.hasMany('clutch_user_permissions', {foreign_key: 'user'})
  .hasMany('clutch_modules', {through: 'clutch_user_permissions', relation: 'clutch_module'})

  .scope('active', function() {
    this.where({status: 1})
  })
})

// ClutchUserPermissions.model.js
store.Model('ClutchUserPermission', function() {
  this.belongsToMany('clutch_user', {primary_key: 'user'})
  .belongsToMany('clutch_module', {primary_key: 'module'})
})

// ClutchModules.model.js
store.Model('ClutchModule', function() {
  this.hasMany('clutch_user_permissions', {foreign_key: 'module'})
  .hasMany('clutch_users', {through: 'clutch_user_permissions'})
})

store.ready(function(){
  const ClutchUsers = store.Model('ClutchUser')
  ClutchUsers.active().include('clutch_modules').exec((records) => {
    console.log(records)
  })
})

```

**Comment by matheusgrieger** [comment]
I see in your example that the `clutch_user_permissions` table you created has an `id` column. Mine doesn't, only `user` and `module` columns, that are foreign keys pointing to the other tables. Tried your solution, didn't work either... Should I be using an `id` column as well?

**Comment by PhilWaldmann** [comment]
Hi Matheus,

nope, my example also works without the `id` column on `clutch_user_permissions `! So that shouldn't be the problem - it's just a preference of designing you schema.

If my above example does not work for you, than there is something else fishy.
You are using openrecord@1.12.4 right? Wich database and version do you use?

**Comment by matheusgrieger** [comment]
Ok so I deleted everything and started from scratch and now it's working. Probably was some mispelling that I didn't see before. Thank you for your help and sorry for taking so much of your time. Your library works great!

Eager to see the new version and full documatation. Keep up the good work and support.

**Comment by PhilWaldmann** [comment]
Awesome! Thanks Matheus
