### ISSUE TITLE
find_by

### ISSUE THREAD

**Issue by amir-s** [PhilWaldmann/openrecord#63]
Hello!

Awesome work! I love how consistent and simple the API is!

I think it worth having a `Model.find_by({key: 'value'})` method like the [`find_by`](http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_by) in ActiveRecord.

It is easier to write
```
const user = await User.find_by({email: 'a@b.c'});
```
comparing to
```
const user = (await User.where({email: 'a@b.c'}).limit(1)).pop();
```

Or maybe there is a similar API that I'm missing?

**Comment by PhilWaldmann** [comment]
Thanks Amir!

Currently there is no equivalent function to the ActiveRecord find_by. But you could easily create a [scope](https://openrecord.js.org/#/definition?id=scopes).

e.g.
```js
// in your model definition
this.scope('find_by_email', function(email){
  this.where({email}).singleResult()
})
```

`singleResult` is not yet documented, but on my todo list! It's a breaking change to version 1 - in V1 limit(1) would return a single record.

So your query would look like this:

```js
const user = await User.find_by_email('a@b.c')
```

If you need a generic `find_by` method, it's better to write a [plugin](https://openrecord.js.org/#/plugins), so it's automatically available to all your models:

```js
// plugins/find_by.js
exports.model = {
  find_by: function(condition){
    return this.where(conditions).singleResult()
  }
}
```

**Comment by PhilWaldmann** [comment]
Instead of `singleResult` You could also write `first`. It‘s an alias

**Comment by amir-s** [comment]
Amazing.
Having it as a plugin is even better. keeping the core as minimal as possible.

Thanks for the explanation. I'm getting more familiar with openrecord as i'm trying to use it to replace sequelizejs in a project of mine.

The documentation needs a bit of work though. I'll try to make prepare some PRs for the docs :)
