### ISSUE TITLE
`where` and `scope` on associations

### ISSUE THREAD

**Issue by amir-s** [PhilWaldmann/openrecord#65]
Is it possible to do something like

```js
let user = await User.find(1);
let posts = await user.posts.where({visible: true});
```
where the user `hasMany('posts')`.

or maybe creating scopes on `Post` model and applying the scope to the relation instead of doing `.where`?

**Comment by amir-s** [comment]
Actually I think there are some issues, what `user.posts` returns is not exactly what something like `Post.where({user_id: 42})` returns.
for example, i can't do `await user.posts.clone()`. It throws:
```js
TypeError: Cannot read property 'chain' of undefined
    at Object.options.getFromCache (/usr/app/node_modules/openrecord/lib/base/relations/bulk_fetch.js:119:82)
    at Object.options.loadWithCollection (/usr/app/node_modules/openrecord/lib/base/relations.js:123:26)
    at Array.exec (/usr/app/node_modules/openrecord/lib/base/exec.js:24:32)
    at Array.then (/usr/app/node_modules/openrecord/lib/base/exec.js:66:17)
    at process._tickCallback (internal/process/next_tick.js:160:7)
```
Also, i think anything that is applied to `user.posts`, should not mutate the state of `user.posts` query itself, so `user.posts` should return a clone if itself.
Currently, if I do `user.posts.count()`, it affects the next query `user.posts.limit(10)`.

**Comment by PhilWaldmann** [comment]
`user.posts.count()` should definitely not affect `user.posts.limit(10)`.
Could you provide an example or test?!

I've just pushed some more relation tests + a few bugfixes. However, I don't think that it will solve any of your described issues.

Thanks,
Phil

**Comment by amir-s** [comment]
Hmmm! ok, i think my mistake was to assign the `user.posts` to another variable, like `let query = user.posts`, and then do `query.count()`, and `query.limit(10)`.

**Comment by amir-s** [comment]
but still, shouldn't I be able to do something like this?
```js
let query = user.posts;
let count = await query.clone().count();
let firstTwo = await query.clone().limit(2);
```

**Comment by PhilWaldmann** [comment]
I've fixed the problem!
`clone` will copy all internal state, even nested objects. Your `query` object has a relation to the `user` record, which is stored inside that internal state. But the cloned record is just an object (it does not clone the prototype!), and therefore does not have any relational information... That's where it crashed!
However, cloning a relation should break the connection to it's parent anyways.

Thanks for your example. I've also added some more test and the ability to do a `record.has_many_through_relation.count()`

**Comment by amir-s** [comment]
awesome!

i just tried with the latest `master` and it seems to be working perfectly!
thanks for the explanation as well 👍 

another quick question, it seems that i have to run `store.ready()` if i want the store to populate the modal `store.Modal('blah')`. again, i don't know if that is expected, maybe it is, and we just need to update the docs.

**Comment by amir-s** [comment]
Another issue that I have found is that creating a relation when creating the model itself, wipes out all the references.

```js
let user1 = await User.create({
  name: 'Amir 1',
  posts: [{
    title: 'post by amir 1',
    visible: true
  }]
});
```
look at the second query:
```
  openrecord:save insert into `users` (`name`) values ('Amir 1') +0ms
  openrecord:save update `posts` set `user_id` = NULL +7ms
  openrecord:save insert into `posts` (`title`, `user_id`, `visible`) values ('post by amir 1', 3, true) +1ms
```

<details>

```js
const Store = require('openrecord/store/sqlite3');

function setup () {
  this.createTable('users', function(){
    this.string('name');
  });
  this.createTable('posts', function () {
    this.string('title');
    this.boolean('visible');
    this.integer('user_id');
  });
}

const store = new Store({
  type: 'sqlite3',
  file: './db.sqlite3',
  autoLoad: true,
  autoSave: true,
  migrations: [
    setup,
  ]
});

class User extends store.BaseModel{
  static definition(){
    this.hasMany('posts');
  }
}
store.Model(User);

class Post extends store.BaseModel{
  static definition(){
    this.belongsTo('user');
  }
}
store.Model(Post);


store.ready(async () => {
  try {
    let user1 = await User.create({
      name: 'Amir 1',
      posts: [{
        title: 'post by amir 1',
        visible: true
      }]
    });
    let user2 = await User.create({
      name: 'Amir 2',
      posts: [{
        title: 'post by amir 2',
        visible: true
      }]
    });

    user1 = await User.find(user1.id);
    user2 = await User.find(user2.id);

    console.log(await user1.posts.count()); // should be 1, but it's zero
    console.log(await user2.posts.count());
    

  }catch (e) {
    console.log("error", e);
  }
});
```
</details>

**Comment by PhilWaldmann** [comment]
That's a feature I've added recently. I hope there are now enough test to call it stable ;)

Thanks for intense testing!

**Comment by amir-s** [comment]
Great! I like one-liner fixes 👍 :D
Tested the latest master, and indeed it works as expected!

Thanks a lot for taking the time! I'm pushing myself to figure out how everything works so I can fix these small things myself :)

I think we can close this issue for good!

**Comment by PhilWaldmann** [comment]
Perfekt! My list for v2.0.0 is almost done... So I'll probably release it today
