### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by matheusgrieger** [PhilWaldmann/openrecord#66]
Hello! Nice to see the revamped 2.0 version, great work! But do you have any plans to add TypeScript support with type declarations? That would be a really nice thing to have!

Thank you for your amazing package!

**Comment by PhilWaldmann** [comment]
Definitely!!

But I think the type declarations need to generated based on your models and their attributes. Otherwise it wont make too much sense, right?

**Comment by pichardoJ** [comment]
Yeah, I think it can be approached with generics.

**Comment by matheusgrieger** [comment]
Yes, I think so too.

But shouldn't OpenRecord have its own types? Not only for code completions within VSCode for example, but also because some TypeScript configs will throw errors because they can't check OpenRecord types ("implicitly has 'any' type").

**Comment by pichardoJ** [comment]
Probably for the context or store api, but for models I agree with @PhilWaldmann it's the user who defines the types.

**Comment by matheusgrieger** [comment]
I agree with you guys. My point when opening this issue was solely for OpenRecord API. Sorry if I couldn't express myself correctly :sweat_smile:

**Comment by PhilWaldmann** [comment]
Typescript support for all available methods is implemented.
