### ISSUE TITLE
Postgresql unknown column type bug

### ISSUE THREAD

**Issue by arthurfranca** [PhilWaldmann/openrecord#71]
Hello, i was upgrading from v1 to v2 and found some issues.

https://github.com/PhilWaldmann/openrecord/blob/7e44a33c859447c7af1510efdf121920bd8283d2/lib/stores/postgres/attributes.js#L6-L7
According to [https://www.postgresql.org/docs/current/static/datatype-numeric.html](https://www.postgresql.org/docs/current/static/datatype-numeric.html),
'small int' should be _smallint_
'big int' should be _bigint_
Didn't test it but i think code should also have keys _smallserial_, _serial_, _bigserial_ as _'integer'_.

I also get "relation ... does not exist" errors for tsvector and geometry (from PostGIS extension) type columns. So maybe you could return _'string'_ instead of null at line 249 for unknown/not listed column types
https://github.com/PhilWaldmann/openrecord/blob/7e44a33c859447c7af1510efdf121920bd8283d2/lib/stores/postgres/attributes.js#L242-L249

**Comment by PhilWaldmann** [comment]
Hey @arthurfranca 

good point! Actually I didn't test with the postgis extension.
I'll take a look at it today or tomorrow. Or if you are faster, a PR is always welcome!

Thanks,
Philipp

**Comment by PhilWaldmann** [comment]
version 2.2 adds more numeric types + all geometric types + fixes.
The default type for unknown postrges types is now `string`. So there shouldn't any errors with postgres extensions and new types.
