### ISSUE TITLE
TypeError: User.create is not a function

### ISSUE THREAD

**Issue by rottenoats** [PhilWaldmann/openrecord#77]
> OpenRecord Version: ^2.7.2
> Node: v11.1.0
> npm: 6.4.1

I'm getting an error when I do the following:

`await User.create(req.body.data)`

When I log User I get this:` [Function: User]`

```
//config/database/openRecord.js
/** more code above */
let store = new Store({
    database, 
    user, 
    password, 
    host,
    autoConnect: true,
    autoAttributes: true,
    models: require("../../app/models/models")
}); 
```

```
//app/models/models.js
module.exports = [
    require("./user")
]
```

```
//app/models/user.js
const Store = require('openrecord/store/mysql');

class User extends Store.BaseModel {
    static definition(){
        this.validatePresenceOf(
            'first_name', 'last_name', 'email', 'password'
        );

        this.validatesConfirmationOf('password');
        this.validateFormatOf('email', 'email');
    }

    fullName(){
        return `${this.first_name} ${this.last_name}`
    }
}

module.exports = User;
```

What am I doing wrong ?

**Comment by PhilWaldmann** [comment]
Hi @rottenoats 

two small typos are `validatePresenceOf` (should be validate**s**PresenceOf) and `validateFormatOf` (should be validate**s**FormatOf).

However, this is not the error you experience!
I'm pretty sure that you forget to wait until the [store is ready](https://openrecord.js.org/#/query).
A simple `await store.ready()` before your `User.create` should solve your problem.  
A better place would be before starting your webserver. (e.g. before `server.listen()` for express)

**Comment by rottenoats** [comment]
@PhilWaldmann thanks for the quick response.

I see where the problem is coming from. So you're recommending I wrap the creation of my webapp in the store.ready() function?

Also would be nice if this was mentioned in the documentation (unless I read too quickly).

https://openrecord.js.org/#/modify?id=createdata

**Comment by PhilWaldmann** [comment]
Thanks for the feedback. I'll make it more clear in the docs!

If you use express (but it's similar with other frameworks) I would do the following:

```js
const express = require('express')
const store = require('./store')

const app = express()

async function start() {
  // add middleware ...

  await store.ready()

  // start express server
  app.listen()
}
start()
```

For usage in [serverless](https://serverless.com/) (or similar frameworks):

```js
// set autoConnect to false
const store = require('./store')

module.handler = await function(event, context, callback){
  store.connect()
  await store.ready()
  // your business logic here
  store.close()
  callback(null, result)
}
```

**Comment by rottenoats** [comment]
@PhilWaldmann thanks for the example, much appreciated. If you have a SO profile you can leave an answer on my [SO question](https://stackoverflow.com/questions/53321488/openrecord-typeerror-user-create-is-not-a-function) if you like.

**Comment by PhilWaldmann** [comment]
sure ;)
