### ISSUE TITLE
Model record suggestions

### ISSUE THREAD

**Issue by arthurfranca** [PhilWaldmann/openrecord#79]
What do you think of exposing/documenting `record.__exists` as there's `record.persisted?` on Rails? Maybe add a `record.isNewRecord` as the opposite of isPersisted/exists
When doing `await record.destroy()` or  `await record.delete()`, assign `false` to record.__exists

Other suggestion: add `await record.update({ ... })` as the same as doing `await record.set({ ... }).save()` for convenience.

**Comment by PhilWaldmann** [comment]
That's a good idea! 

Thanks

**Comment by PhilWaldmann** [comment]
available in v2.8.0
