### ISSUE TITLE
Help with Transaction, please

### ISSUE THREAD

**Issue by arthurfranca** [PhilWaldmann/openrecord#80]
Hello, tried using transaction like:
```javascript
await new Promise(resolve => store.startTransaction(resolve))
  .then(trx => Promise.all(
    [Model1.useTransaction(trx).create({ valid: 12 }),
    Model2.useTransaction(trx).create({ invalid: 'a validation error' })]
  ))
```

But the validation error on Model2 did not prevent Model1 record creation, so there was no rollback. Is transaction available or am i using it wrong?

**Comment by PhilWaldmann** [comment]
```js
await store.startTransaction(trx => {
  return Promise.all([
    Model1.useTransaction(trx).create({ valid: 12 }),
    Model2.useTransaction(trx).create({ invalid: 'a validation error' })
  ])
})
```
should do the trick.

**Comment by PhilWaldmann** [comment]
Hmm... that's strange!
I'll test it later today!

**Comment by PhilWaldmann** [comment]
Hi @arthurfranca 

I had a bug in my tests which was hiding a bug inside openrecord.
Please install v2.8.1 which should fix the problem you are facing.

**Comment by arthurfranca** [comment]
One more thing, it seems there's no useTransaction when record is already loaded.

I think it would be a nice addition being able to do something like this:
```javascript
await store.startTransaction(tx => {
 return Promise.all([
    record.save(tx) // or record.save().useTransaction(tx) or record.useTransaction(tx).save()
    record.update({}, tx) // or record.update({}).useTransaction(tx) or record.useTransaction(tx).update({})
  ])
})
```

**Comment by PhilWaldmann** [comment]
`save()` takes an optional param `options`. So you could do the following:

```js
await store.startTransaction(transaction => {
 return Promise.all([
    record.save({transaction})
  ])
})
```

It's not yet documented, but used internally.
I'll add documentation and also enhance `update()` and `create()` to support the same options object.

**Comment by PhilWaldmann** [comment]
Documentation is online.
Thanks for your support!
