### ISSUE TITLE
Single-table inheritance support?

### ISSUE THREAD

**Issue by jfrux** [PhilWaldmann/openrecord#85]
Looking for an example of single-table inheritance similar to Rails... is this possible with your library?
I have an existing database that is using this and was trying to build models around it but I could just use a single model and scopes I suppose but was trying to make it more like its Rails counterpart.

Thanks and great job!

**Comment by PhilWaldmann** [comment]
if you want to share common functionality between models, try [mixins](https://openrecord.js.org/#/definition?id=mixins). But pointing multiple models to the same table is currently not supported.
