### ISSUE TITLE
table name error

### ISSUE THREAD

**Issue by xualen** [PhilWaldmann/openrecord#86]
Thanks for a great library.  there is a table(admin) in mysql, i use "store.Model('admin');". node js log error "Error: ER_NO_SUCH_TABLE: Table 'test.admins' doesn't exist"

**Comment by PhilWaldmann** [comment]
Hi @xualen 

thanks!

openrecord always pluralize model names to get the table name. In your case, you need to tell openrecord not to do so:

```js
const store = new Store({
  // your config here...
  inflection: {
    'admins' : 'admin'
  }
})
```

**Comment by xualen** [comment]
@PhilWaldmann  thanks

**Comment by xualen** [comment]
@PhilWaldmann , i hava another question. is there transaction in openrecord?

**Comment by xualen** [comment]
@PhilWaldmann thanks. but i have a another question. is there transaction in openrecord?

**Comment by PhilWaldmann** [comment]
sure: https://openrecord.js.org/#/modify?id=transactions

**Comment by xualen** [comment]
@PhilWaldmann thank u. is openrecord support lock tables?

**Comment by PhilWaldmann** [comment]
not out of the box.

but it should be possible via: 

```js

await store.startTransaction(trx => {
  store.connection.transacting(trx).raw('LOCK TABLE...')
  .then(() => {
    ...
  })
})
```

The above code is not tested!! 
`store.connection` returns a [knex](https://knexjs.org/) instance.
`transacting` and `raw` are knex functions!

let me know if that works for you.

Thanks,
Philipp

**Comment by xualen** [comment]
@PhilWaldmann thanks for your answer.
