### ISSUE TITLE
Model.find() with empty argument has an unexpected return

### ISSUE THREAD

**Issue by arthurfranca** [PhilWaldmann/openrecord#90]
`await Model.find(/*null or undefined*/)` is returning the same as `await Model.first()`

So when one writes `await Model.find(req.params.id)` on Express with an empty id, it will inadvertently show or edit the wrong object.

Maybe it's best to return `undefined`, just like when finding by a primary key value absent from DB. Like if the query were `select * from model where id is null limit 1`.

**Comment by PhilWaldmann** [comment]
Wow, that totally got unnoticed for a while!
Thanks for finding this bug. I'll fix it, give me a moment.

**Comment by PhilWaldmann** [comment]
fixed with version `2.8.5`

Thanks @arthurfranca
